# Generated by Django 5.0.3 on 2024-03-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=150, verbose_name='endereço')),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(verbose_name='nível')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150, verbose_name='descrição')),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pontos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='campo',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descrição'),
        ),
    ]
