# Generated by Django 5.0.3 on 2025-04-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ultimo_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
