# Generated by Django 5.0.3 on 2025-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32mqtt', '0003_medicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tempo_online_acumulado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_entrada_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
