# Generated by Django 5.0.3 on 2025-05-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='assignee',
            field=models.CharField(default=10, max_length=100, verbose_name='Responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('professional', 'Profissional'), ('personal', 'Pessoal')], default=102030, max_length=12, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
